version: '3.8'

networks:
  global_network:
    external: true

services:
  cos_frontend:
    image: 'node:16.15-alpine3.15'
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  "3001:3000"
    networks:
      - global_network

